name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: grupo28
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t grupo28/tc-cadastro:latest .
          docker push grupo28/tc-cadastro:latest